// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// et_distance_objective
Rcpp::List et_distance_objective(arma::vec lambda_exact, arma::vec theta_extended, arma::mat return_matrix, double mu_penalty);
RcppExport SEXP _entRsdf_et_distance_objective(SEXP lambda_exactSEXP, SEXP theta_extendedSEXP, SEXP return_matrixSEXP, SEXP mu_penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lambda_exact(lambda_exactSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_extended(theta_extendedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type return_matrix(return_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type mu_penalty(mu_penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(et_distance_objective(lambda_exact, theta_extended, return_matrix, mu_penalty));
    return rcpp_result_gen;
END_RCPP
}
// et_distance_theta_gradient
arma::mat et_distance_theta_gradient(arma::vec lambda_opt, arma::vec theta_extended, arma::mat return_matrix, double mu_penalty);
RcppExport SEXP _entRsdf_et_distance_theta_gradient(SEXP lambda_optSEXP, SEXP theta_extendedSEXP, SEXP return_matrixSEXP, SEXP mu_penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lambda_opt(lambda_optSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_extended(theta_extendedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type return_matrix(return_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type mu_penalty(mu_penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(et_distance_theta_gradient(lambda_opt, theta_extended, return_matrix, mu_penalty));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_entRsdf_et_distance_objective", (DL_FUNC) &_entRsdf_et_distance_objective, 4},
    {"_entRsdf_et_distance_theta_gradient", (DL_FUNC) &_entRsdf_et_distance_theta_gradient, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_entRsdf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
