# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

et_distance_objective <- function(lambda_exact, theta_extended, return_matrix, mu_penalty) {
    .Call(`_entRsdf_et_distance_objective`, lambda_exact, theta_extended, return_matrix, mu_penalty)
}

et_distance_individual <- function(lambda_exact, theta_extended, return_matrix) {
    .Call(`_entRsdf_et_distance_individual`, lambda_exact, theta_extended, return_matrix)
}

et_distance_theta_gradient <- function(lambda_opt, theta_extended, return_matrix, mu_penalty) {
    .Call(`_entRsdf_et_distance_theta_gradient`, lambda_opt, theta_extended, return_matrix, mu_penalty)
}

